default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 100 } %>

development:
  <<: *default
  database: bookshop_development

test:
  adapter: sqlite3
  database: db/test.sqlite3
